export const topClassData = [
  {
    class_no: '0011',
    class_name: '電腦&周邊',
    index: 0,
    index1: 0,
    img: require('./newCategory/category0011.png'),
    img1: require('./newCategory/category0011-active.png'),
  },
  {
    class_no: '0021',
    class_name: '手機通訊',
    index: 1,
    index1: 0,
    img: require('./newCategory/category0021.png'),
    img1: require('./newCategory/category0021-active.png'),
  },
  {
    class_no: '0023',
    class_name: '家電影音',
    index: 2,
    index1: 0,
    img: require('./newCategory/category0023.png'),
    img1: require('./newCategory/category0023-active.png'),
  },
  {
    class_no: '0019',
    class_name: '交通工具',
    index: 3,
    index1: 0,
    img: require('./newCategory/category0019.png'),
    img1: require('./newCategory/category0019-active.png'),
  },
  {
    class_no: '0008',
    class_name: '相機攝影',
    index: 4,
    index1: 1,
    img: require('./newCategory/category0008.png'),
    img1: require('./newCategory/category0008-active.png'),
  },
  {
    class_no: '0005',
    class_name: '玩具公仔',
    index: 5,
    index1: 1,
    img: require('./newCategory/category0005.png'),
    img1: require('./newCategory/category0005-active.png'),
  },
  {
    class_no: '0010',
    class_name: '音樂電影',
    index: 6,
    index1: 1,
    img: require('./newCategory/category0010.png'),
    img1: require('./newCategory/category0010-active.png'),
  },
  {
    class_no: '0004',
    class_name: '明星偶像',
    index: 7,
    index1: 1,
    img: require('./newCategory/category0004.png'),
    img1: require('./newCategory/category0004-active.png'),
  },
  {
    class_no: '0017',
    class_name: '鐘錶眼鏡',
    index: 8,
    index1: 2,
    img: require('./newCategory/category0017.png'),
    img1: require('./newCategory/category0017-active.png'),
  },
  {
    class_no: '0013',
    class_name: '古董收藏',
    index: 9,
    index1: 2,
    img: require('./newCategory/category0013.png'),
    img1: require('./newCategory/category0013-active.png'),
  },
  {
    class_no: '0007',
    class_name: '房屋&服務',
    index: 10,
    index1: 2,
    img: require('./newCategory/category0007.png'),
    img1: require('./newCategory/category0007-active.png'),
  },
  {
    class_no: '0022',
    class_name: '電玩遊戲',
    index: 11,
    index1: 2,
    img: require('./newCategory/category0022.png'),
    img1: require('./newCategory/category0022-active.png'),
  },
  {
    class_no: '0002',
    class_name: '女裝內睡衣',
    index: 12,
    index1: 3,
    img: require('./newCategory/category0002.png'),
    img1: require('./newCategory/category0002-active.png'),
  },
  {
    class_no: '0014',
    class_name: '女性飾品',
    index: 13,
    index1: 3,
    img: require('./newCategory/category0014.png'),
    img1: require('./newCategory/category0014-active.png'),
  },
  {
    class_no: '0015',
    class_name: '女包女鞋',
    index: 14,
    index1: 3,
    img: require('./newCategory/category0015.png'),
    img1: require('./newCategory/category0015-active.png'),
  },
  {
    class_no: '0001',
    class_name: '嬰幼&母親',
    index: 15,
    index1: 3,
    img: require('./newCategory/category0001.png'),
    img1: require('./newCategory/category0001-active.png'),
  },
  {
    class_no: '0006',
    class_name: '書刊文具',
    index: 16,
    index1: 4,
    img: require('./newCategory/category0006.png'),
    img1: require('./newCategory/category0006-active.png'),
  },
  {
    class_no: '0009',
    class_name: '生活居家',
    index: 17,
    index1: 4,
    img: require('./newCategory/category0009.png'),
    img1: require('./newCategory/category0009-active.png'),
  },
  {
    class_no: '0018',
    class_name: '男裝配件',
    index: 18,
    index1: 4,
    img: require('./newCategory/category0018.png'),
    img1: require('./newCategory/category0018-active.png'),
  },
  {
    class_no: '0003',
    class_name: '運動健身',
    index: 19,
    index1: 4,
    img: require('./newCategory/category0003.png'),
    img1: require('./newCategory/category0003-active.png'),
  },
  {
    class_no: '0020',
    class_name: '休閒旅遊',
    index: 20,
    index1: 5,
    img: require('./newCategory/category0020.png'),
    img1: require('./newCategory/category0020-active.png'),
  },
  {
    class_no: '0024',
    class_name: '名產食品',
    index: 21,
    index1: 5,
    img: require('./newCategory/category0024.png'),
    img1: require('./newCategory/category0024-active.png'),
  },
  {
    class_no: '0012',
    class_name: '保養彩妝',
    index: 22,
    index1: 5,
    img: require('./newCategory/category0012.png'),
    img1: require('./newCategory/category0012-active.png'),
  },
  {
    class_no: '0025',
    class_name: '成人專區',
    index: 23,
    index1: 5,
    img: require('./newCategory/category0025.png'),
    img1: require('./newCategory/category0025-active.png'),
  },
];

export const dataForSectionList = [
  {
    index: '0',
    data: [
      {
        class_no: '0011',
        class_name: '電腦&周邊',
        rowIndex: '0',
        img: require('./newCategory/category0011.png'),
        img1: require('./newCategory/category0011-active.png'),
      },
      {
        class_no: '0021',
        class_name: '手機通訊',
        rowIndex: '0',
        img: require('./newCategory/category0021.png'),
        img1: require('./newCategory/category0021-active.png'),
      },
      {
        class_no: '0023',
        class_name: '家電影音',
        rowIndex: '0',
        img: require('./newCategory/category0023.png'),
        img1: require('./newCategory/category0023-active.png'),
      },
      {
        class_no: '0019',
        class_name: '交通工具',
        rowIndex: '0',
        img: require('./newCategory/category0019.png'),
        img1: require('./newCategory/category0019-active.png'),
      },
    ],
  },
  {
    index: '1',
    data: [
      {
        class_no: '0008',
        class_name: '相機攝影',
        rowIndex: '1',
        img: require('./newCategory/category0008.png'),
        img1: require('./newCategory/category0008-active.png'),
      },
      {
        class_no: '0005',
        class_name: '玩具公仔',
        rowIndex: '1',
        img: require('./newCategory/category0005.png'),
        img1: require('./newCategory/category0005-active.png'),
      },
      {
        class_no: '0010',
        class_name: '音樂電影',
        rowIndex: '1',
        img: require('./newCategory/category0010.png'),
        img1: require('./newCategory/category0010-active.png'),
      },
      {
        class_no: '0004',
        class_name: '明星偶像',
        rowIndex: '1',
        img: require('./newCategory/category0004.png'),
        img1: require('./newCategory/category0004-active.png'),
      },
    ],
  },
  {
    index: '2',
    data: [
      {
        class_no: '0017',
        class_name: '鐘錶眼鏡',
        rowIndex: '2',
        img: require('./newCategory/category0017.png'),
        img1: require('./newCategory/category0017-active.png'),
      },
      {
        class_no: '0013',
        class_name: '古董收藏',
        rowIndex: '2',
        img: require('./newCategory/category0013.png'),
        img1: require('./newCategory/category0013-active.png'),
      },
      {
        class_no: '0007',
        class_name: '房屋&服務',
        rowIndex: '2',
        img: require('./newCategory/category0007.png'),
        img1: require('./newCategory/category0007-active.png'),
      },
      {
        class_no: '0022',
        class_name: '電玩遊戲',
        rowIndex: '2',
        img: require('./newCategory/category0022.png'),
        img1: require('./newCategory/category0022-active.png'),
      },
    ],
  },
  {
    index: '3',
    data: [
      {
        class_no: '0002',
        class_name: '女裝內睡衣',
        rowIndex: '3',
        img: require('./newCategory/category0002.png'),
        img1: require('./newCategory/category0002-active.png'),
      },
      {
        class_no: '0014',
        class_name: '女性飾品',
        rowIndex: '3',
        img: require('./newCategory/category0014.png'),
        img1: require('./newCategory/category0014-active.png'),
      },
      {
        class_no: '0015',
        class_name: '女包女鞋',
        rowIndex: '3',
        img: require('./newCategory/category0015.png'),
        img1: require('./newCategory/category0015-active.png'),
      },
      {
        class_no: '0001',
        class_name: '嬰幼&母親',
        rowIndex: '3',
        img: require('./newCategory/category0001.png'),
        img1: require('./newCategory/category0001-active.png'),
      },
    ],
  },
  {
    index: '4',
    data: [
      {
        class_no: '0006',
        class_name: '書刊文具',
        rowIndex: '4',
        img: require('./newCategory/category0006.png'),
        img1: require('./newCategory/category0006-active.png'),
      },
      {
        class_no: '0009',
        class_name: '生活居家',
        rowIndex: '4',
        img: require('./newCategory/category0009.png'),
        img1: require('./newCategory/category0009-active.png'),
      },
      {
        class_no: '0018',
        class_name: '男裝配件',
        rowIndex: '4',
        img: require('./newCategory/category0018.png'),
        img1: require('./newCategory/category0018-active.png'),
      },
      {
        class_no: '0003',
        class_name: '運動健身',
        rowIndex: '4',
        img: require('./newCategory/category0003.png'),
        img1: require('./newCategory/category0003-active.png'),
      },
    ],
  },
  {
    index: '5',
    data: [
      {
        class_no: '0020',
        class_name: '休閒旅遊',
        rowIndex: '5',
        img: require('./newCategory/category0020.png'),
        img1: require('./newCategory/category0020-active.png'),
      },
      {
        class_no: '0024',
        class_name: '名產食品',
        rowIndex: '5',
        img: require('./newCategory/category0024.png'),
        img1: require('./newCategory/category0024-active.png'),
      },
      {
        class_no: '0012',
        class_name: '保養彩妝',
        rowIndex: '5',
        img: require('./newCategory/category0012.png'),
        img1: require('./newCategory/category0012-active.png'),
      },
      {
        class_no: '0025',
        class_name: '成人專區',
        rowIndex: '5',
        img: require('./newCategory/category0025.png'),
        img1: require('./newCategory/category0025-active.png'),
      },
    ],
  },
];
